// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FitNetClean.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FitNetContext))]
    [Migration("20260120090323_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContraIndicationEquipment", b =>
                {
                    b.Property<long>("ContraIndicationListId")
                        .HasColumnType("bigint");

                    b.Property<long>("EquipmentListId")
                        .HasColumnType("bigint");

                    b.HasKey("ContraIndicationListId", "EquipmentListId");

                    b.HasIndex("EquipmentListId");

                    b.ToTable("ContraIndicationEquipment");
                });

            modelBuilder.Entity("ContraIndicationExercise", b =>
                {
                    b.Property<long>("ContraIndicationListId")
                        .HasColumnType("bigint");

                    b.Property<long>("ExerciseListId")
                        .HasColumnType("bigint");

                    b.HasKey("ContraIndicationListId", "ExerciseListId");

                    b.HasIndex("ExerciseListId");

                    b.ToTable("ContraIndicationExercise");
                });

            modelBuilder.Entity("FitNetClean.Domain.Entities.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("FitNetClean.Domain.Entities.ContraIndication", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("ContraIndication");
                });

            modelBuilder.Entity("FitNetClean.Domain.Entities.Equipment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("FitNetClean.Domain.Entities.Exercise", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("EquipmentId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long?>("WorkoutGroupId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkoutId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.HasIndex("WorkoutGroupId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("FitNetClean.Domain.Entities.Workout", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Workout");
                });

            modelBuilder.Entity("FitNetClean.Domain.Entities.WorkoutGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("WorkoutId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("WorkoutGroup");
                });

            modelBuilder.Entity("ContraIndicationEquipment", b =>
                {
                    b.HasOne("FitNetClean.Domain.Entities.ContraIndication", null)
                        .WithMany()
                        .HasForeignKey("ContraIndicationListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitNetClean.Domain.Entities.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContraIndicationExercise", b =>
                {
                    b.HasOne("FitNetClean.Domain.Entities.ContraIndication", null)
                        .WithMany()
                        .HasForeignKey("ContraIndicationListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FitNetClean.Domain.Entities.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExerciseListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FitNetClean.Domain.Entities.Equipment", b =>
                {
                    b.HasOne("FitNetClean.Domain.Entities.Category", "Category")
                        .WithMany("EquipmentList")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FitNetClean.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("FitNetClean.Domain.Entities.Equipment", "Equipment")
                        .WithMany("ExerciseList")
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitNetClean.Domain.Entities.WorkoutGroup", "WorkoutGroup")
                        .WithMany("ExerciseList")
                        .HasForeignKey("WorkoutGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FitNetClean.Domain.Entities.Workout", "Workout")
                        .WithMany("ExerciseList")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("FitNetClean.Domain.Entities.Measurement", "Repetition", b1 =>
                        {
                            b1.Property<long>("ExerciseId")
                                .HasColumnType("bigint");

                            b1.Property<double>("Quantity")
                                .HasColumnType("double precision");

                            b1.Property<int>("Unit")
                                .HasColumnType("integer");

                            b1.HasKey("ExerciseId");

                            b1.ToTable("Measurement");

                            b1.WithOwner()
                                .HasForeignKey("ExerciseId");
                        });

                    b.Navigation("Equipment");

                    b.Navigation("Repetition")
                        .IsRequired();

                    b.Navigation("Workout");

                    b.Navigation("WorkoutGroup");
                });

            modelBuilder.Entity("FitNetClean.Domain.Entities.WorkoutGroup", b =>
                {
                    b.HasOne("FitNetClean.Domain.Entities.Workout", "Workout")
                        .WithMany("WorkoutGroupList")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("FitNetClean.Domain.Entities.Category", b =>
                {
                    b.Navigation("EquipmentList");
                });

            modelBuilder.Entity("FitNetClean.Domain.Entities.Equipment", b =>
                {
                    b.Navigation("ExerciseList");
                });

            modelBuilder.Entity("FitNetClean.Domain.Entities.Workout", b =>
                {
                    b.Navigation("ExerciseList");

                    b.Navigation("WorkoutGroupList");
                });

            modelBuilder.Entity("FitNetClean.Domain.Entities.WorkoutGroup", b =>
                {
                    b.Navigation("ExerciseList");
                });
#pragma warning restore 612, 618
        }
    }
}
